---
- hosts: all
  sudo: true
  vars:
    dbname: food_mixer
    dbuser: vagrant
    dbpassword: devpassword # probably not a the best practice but we are using this for dev only
  tasks:
    - name: Install pip3
      apt:
        name: python3-pip
        state: present
        update_cache: yes
    - name: Install requirements
      pip:
        requirements: "/srv/mixer-api/requirements.txt"
        executable: pip3
    - name: run server
      command: gunicorn backend:app -D -b 0.0.0.0:8000 chdir=/srv/mixer-api

    - name: ensure apt cache is up to date
      apt: update_cache=yes
    - name: ensure packages are installed
      apt: name={{item}}
      with_items:
        - postgresql
        - libpq-dev
        - python-psycopg2
    - name: ensure database is created
      become: true
      become_user: postgres
      postgresql_db: name={{dbname}}
    - name: ensure user has access to database
      become: true
      become_user: postgres
      postgresql_user: db={{dbname}} name={{dbuser}} password={{dbpassword}} priv=ALL
    - name: ensure user does not have unnecessary privilege
      become: true
      become_user: postgres
      postgresql_user: name={{dbuser}} role_attr_flags=NOSUPERUSER,NOCREATEDB
    - name: ensure no other user can access the database
      become: true
      become_user: postgres
      postgresql_privs: db={{dbname}} role=PUBLIC type=database priv=ALL state=absent
